#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
#mybatis:
#  typeAliasesPackage: com.czh.demo.enity
#  mapper-locations: classpath*:/mybatis/mapper/*.xml
#  mapperLocations: classpath:com/czh/demo/mapper/*.xml

#mybatis.mapper-locations: classpath*:/mybatis/mapper/*.xml
mybatis.typeAliasesPackage: com.czh.demo.enity


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 232423
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource